[[index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true

[[index]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

[[index]]
name = "ustc"
url = "https://pypi.mirrors.ustc.edu.cn/simple/"

[[index]]
name = "pypi"
url = "https://pypi.org/simple"
