[[rulesets]]
group = "ğŸ¼ å…¨çƒç›´è¿"
ruleset = "force-direct.txt"
interval = 86400

[[rulesets]]
group = "ğŸª Match"
ruleset = "force-proxy.txt"
interval = 86400

[[rulesets]]
group = "ğŸ» Chat"
ruleset = "chat.txt"
interval = 86400

[[rulesets]]
group = "ğŸ» Chat"
ruleset = "openai.txt"
interval = 86400

[[rulesets]]
group = "ğŸ¼ å…¨çƒç›´è¿"
ruleset = "direct.txt"
interval = 86400

[[rulesets]]
group = "DIRECT"
ruleset = "lan_cidr.txt"
interval = 86400

# [[rulesets]]
# group = "ğŸŒ» èŠ‚ç‚¹é€‰æ‹©"
# ruleset = "rules/proxy.txt"
# interval = 86400
#
# [[rulesets]]
# group = "ğŸŒ» èŠ‚ç‚¹é€‰æ‹©"
# ruleset = "rules/gfw.txt"
# interval = 86400

[[rulesets]]
group = "ğŸª Match"
ruleset = "MATCH"
