[[custom_groups]]
name = "ğŸŒ» èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = [
  "[]ğŸŒ² è´Ÿè½½å‡è¡¡-è½®è¯¢",
  "[]ğŸ è´Ÿè½½å‡è¡¡-æ•£åˆ—",
  "[]ğŸ æ‰‹åŠ¨åˆ‡æ¢",
  "[]ğŸ‡­ğŸ‡° é¦™æ¸¯",
  "[]ğŸ‡¹ğŸ‡¼ å°æ¹¾",
  "[]ğŸ‡¸ğŸ‡¬ ç‹®åŸ",
  "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬",
  "[]ğŸ‡ºğŸ‡² ç¾å›½",
  "[]ğŸ‡°ğŸ‡· éŸ©å›½",
  "[]ğŸ‡®ğŸ‡³ å°åº¦",
  "[]ğŸ‡¹ğŸ‡· åœŸè€³å…¶",
]

[[custom_groups]]
name = "ğŸŒ² è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["é¦™æ¸¯[^-]|å°æ¹¾|æ—¥æœ¬"]

[[custom_groups]]
name = "ğŸ è´Ÿè½½å‡è¡¡-æ•£åˆ—"
type = "load-balance"
strategy = "consistent-hashing"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["é¦™æ¸¯[^-]|å°æ¹¾|æ—¥æœ¬"]

[[custom_groups]]
name = "ğŸ æ‰‹åŠ¨åˆ‡æ¢"
type = "select"
rule = ["^(?!.*(å¥—é¤|åˆ°æœŸ|å‰©ä½™|æµé‡|é‡ç½®|æ—¶é—´|å®˜ç½‘|äº§å“|ä¸Šç½‘|æ›´æ–°|è®¢é˜…|å¹³å°|expire)).*"]

[[custom_groups]]
name = "ğŸ¼ å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT", "[]ğŸŒ» èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ» Chat"
type = "select"
rule = ["[]ğŸ‡®ğŸ‡³ å°åº¦", "[]ğŸ‡¹ğŸ‡· åœŸè€³å…¶", "[]ğŸ‡°ğŸ‡· éŸ©å›½", "[]ğŸ‡ºğŸ‡² ç¾å›½", "[]ğŸ æ‰‹åŠ¨åˆ‡æ¢"]

[[custom_groups]]
name = "ğŸ¦ å¹¿å‘Šæ‹¦æˆª"
type = "select"
rule = ["[]REJECT", "[]ğŸ¼ å…¨çƒç›´è¿"]

[[custom_groups]]
name = "ğŸª Match"
type = "select"
rule = ["[]ğŸŒ» èŠ‚ç‚¹é€‰æ‹©", "[]DIRECT"]

[[custom_groups]]
name = "ğŸ FallBack"
type = "fallback"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["åº”æ€¥|ä¸“çº¿|IEPL"]

[[custom_groups]]
name = "ğŸŒˆ è®¢é˜…ä¿¡æ¯"
type = "select"
rule = ["å¥—é¤|åˆ°æœŸ|å‰©ä½™|æµé‡|é‡ç½®|æ—¶é—´|å®˜ç½‘|äº§å“|ä¸Šç½‘|æ›´æ–°|è®¢é˜…|å¹³å°|expire"]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["é¦™æ¸¯[^-]|HK|Hong Kong"]

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ å°æ¹¾"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan"]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ç‹®åŸ"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore"]

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan"]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States"]

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["éŸ©å›½|éŸ©|é¦–å°”|éŸ“|KR|Korea|KOR"]

[[custom_groups]]
name = "ğŸ‡®ğŸ‡³ å°åº¦"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["å°åº¦|å­Ÿä¹°|India"]

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡· åœŸè€³å…¶"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["åœŸè€³å…¶|ä¼Šæ–¯å¦å¸ƒå°”|TR|Turkey"]

[[custom_groups]]
name = "ğŸ‡»ğŸ‡³ è¶Šå—"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["è¶Šå—"]

[[custom_groups]]
name = "ğŸ‡µğŸ‡­ è²å¾‹å®¾"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["è²å¾‹å®¾"]

[[custom_groups]]
name = "ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºš"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["é©¬æ¥è¥¿äºš"]

[[custom_groups]]
name = "ğŸ‡¦ğŸ‡º æ¾³å¤§åˆ©äºš"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["æ¾³å¤§åˆ©äºš"]

[[custom_groups]]
name = "ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["ä¿„ç½—æ–¯"]

[[custom_groups]]
name = "ğŸ‡¬ğŸ‡§ è‹±å›½"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["è‹±å›½"]

[[custom_groups]]
name = "ğŸ‡©ğŸ‡ª å¾·å›½"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["å¾·å›½"]

[[custom_groups]]
name = "ğŸ‡«ğŸ‡· æ³•å›½"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["æ³•å›½"]

[[custom_groups]]
name = "ğŸ‡³ğŸ‡± è·å…°"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["è·å…°"]

[[custom_groups]]
name = "ğŸ‡·ğŸ‡´ ç½—é©¬å°¼äºš"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["ç½—é©¬å°¼äºš"]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¦ ä¹Œå…‹å…°"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["ä¹Œå…‹å…°"]

[[custom_groups]]
name = "ğŸ‡µğŸ‡± æ³¢å…°"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["æ³¢å…°"]

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["åŠ æ‹¿å¤§"]

[[custom_groups]]
name = "ğŸ‡®ğŸ‡± ä»¥è‰²åˆ—"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["ä»¥è‰²åˆ—"]

[[custom_groups]]
name = "ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["é˜¿æ ¹å»·"]

[[custom_groups]]
name = "ğŸ‡±ğŸ‡º å¢æ£®å ¡"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["å¢æ£®å ¡"]

[[custom_groups]]
name = "ğŸ‡¦ğŸ‡¹ å¥¥åœ°åˆ©"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["å¥¥åœ°åˆ©"]

[[custom_groups]]
name = "ğŸ‡¦ğŸ‡¶ å—æ"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 180
tolerance = 100
rule = ["å—æ"]
