[general]
live_config_reload = true
import = ["~/.config/alacritty/colors/github_dark_default.toml"]

[env]
TERM = "tmux-256color"
QT_IM_MODULE = "fcitx"

[font]
builtin_box_drawing = true
size = 10.0

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[font.italic]
family = "Maple Mono NF CN"
style = "Italic"

[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdlsahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
blur = true
opacity = 0.8

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 8

[window.position]
x = 0
y = 0
